### PR TITLE
feat: AD-238 Add AWS::RDS::DBClusterSnapshot

### PR DESCRIPTION
**Pull request by hemen-plerion**

### CODE REVIEW

**Review by plerionedmund — COMMENTED** [review]
You'll need to add it here: https://github.com/plerionhq/plerion-asset-counter/blob/main/AWS/aws-dependencies.json

**Comment by hemen-plerion** [comment]
> You'll need to add it here: https://github.com/plerionhq/plerion-asset-counter/blob/main/AWS/aws-dependencies.json

@plerionedmund, why other RDS resources are not added there?

**Comment by plerionedmund** [comment]
@hemen-plerion [they're in the code and not the dependencies file](https://github.com/plerionhq/plerion-asset-counter/blob/main/AWS/aws.js#L687)

**Review by plerionedmund — APPROVED** [review]
Approved but please remove the additional entries in aws-dependencies.json

**Pull request merged**
