### PR TITLE
feat: CSPM-1261 Filtering out ASG and terminated instances

### PR DESCRIPTION
**Pull request by edmundcong**

### CODE REVIEW

**Review by sakadoddle — APPROVED** [review]
LGMT 👍

**Comment by shankarPlerion** [comment]
@edmundcong, could we update this branch with latest changes and resolve merge conflict in this PR. 
I'm planning to check out my changes for https://plerion.atlassian.net/browse/CWPP-1034 from this branch.

**Comment by shankarPlerion** [comment]
Should we close this PR @edmundcong since we are same thing in #35 ?

**Comment by plerion-swojeet** [comment]
Closing this PR as the same change is covered by https://github.com/plerionhq/plerion-asset-counter/pull/35

**Pull request closed without merging**
